language: ruby

rvm: '2.3.0'

script: bundle exec rspec spec

# script:
#   - mkdir -p spec && bundle exec rake db:auto_migrate RACK_ENV=test

before_install:
- sed -i '2d' Gemfile
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database makersbnb_test;' -U postgres

notifications:
  email: false
